/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Cards/Card.vue')['default']
    ChartCard: typeof import('./src/components/Cards/ChartCard.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCustomTable: typeof import('./src/components/custom/ElCustomTable.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputField: typeof import('./src/components/fields/ElInputField.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconInfoCircle: typeof import('./src/components/icons/IconInfoCircle.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    KnowledgeBaseHeader: typeof import('./src/components/knowledge-base/KnowledgeBaseHeader.vue')['default']
    KnowledgeBaseModal: typeof import('./src/components/knowledge-base/KnowledgeBaseModal.vue')['default']
    KnowledgeBaseSelect: typeof import('./src/components/knowledge-base/KnowledgeBaseSelect.vue')['default']
    KnowledgeBaseTabs: typeof import('./src/components/knowledge-base/KnowledgeBaseTabs.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    SidebarMenu: typeof import('./src/components/SidebarMenu.vue')['default']
    StatsCard: typeof import('./src/components/Cards/StatsCard.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TextInput: typeof import('./src/components/input/TextInput.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
